name: Build and Deploy ADF from Dev to UAT
on:
  push:
    branches:
      - develop
jobs:
  deploy-adf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Validate ARM Template
      uses: azure/arm-deploy@v1
      with:
        scope: "resourcegroup"
        resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP }}
        template: "./SalesPipelineFactoryDev/factory/SalesPipelineFactoryDev_ARMTemplateForFactory.json"
        parameters: "./SalesPipelineFactoryDev/factory/SalesPipelineFactoryDev_ARMTemplateParametersForFactory.json"
        additional-parameters: factoryName=${{ secrets.ADF_NAME_UAT }}
        deployment-mode: Validate
    - name: Deploy ADF ARM Template
      uses: azure/arm-deploy@v1
      with:
        scope: "resourcegroup"
        resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP }}
        template: "./SalesPipelineFactoryDev/factory/SalesPipelineFactoryDev_ARMTemplateForFactory.json"
        parameters: "./SalesPipelineFactoryDev/factory/SalesPipelineFactoryDev_ARMTemplateParametersForFactory.json"
        additional-parameters: >
          factoryName=${{ secrets.ADF_NAME_UAT }}
        deployment-mode: Incremental