name: Deploy ADF Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'adf/**'
  workflow_dispatch:

jobs:
  deploy-to-uat:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ARM templates
        uses: actions/download-artifact@v3
        with:
          name: arm-templates
          path: arm-templates/

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Create UAT parameters file
        run: |
          cat > arm-templates/parameters-uat.json << EOF_NESTED
          {
            "\$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
            "contentVersion": "1.0.0.0",
            "parameters": {
              "factoryName": {
                "value": "SalesPipelineFactoryUAT"
              },
              "AzureBlobStorage_connectionString": {
                "value": "DefaultEndpointsProtocol=https;AccountName=${{ secrets.STORAGE_ACCOUNT_NAME }};AccountKey=${{ secrets.STORAGE_ACCOUNT_KEY }};EndpointSuffix=core.windows.net"
              }
            }
          }
          EOF_NESTED

      - name: Deploy to UAT
        run: |
          az deployment group create \
            --resource-group SalesPipelineRG \
            --template-file arm-templates/ARMTemplateForFactory.json \
            --parameters @arm-templates/parameters-uat.json
