name: Build and Deploy ADF from Dev to UAT
on:
  push:
    branches:
      - develop
jobs:
  deploy-adf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Added client secret authentication
    - name: Deploy ADF ARM Template
      uses: azure/arm-deploy@v1
      with:
        scope: "resourcegroup"
        resource-group: ${{ secrets.ADF_RESOURCE_GROUP }}
        template: "./adf_publish/ARMTemplateForFactory.json"
        parameters: "./adf_publish/ARMTemplateParametersForFactory.json"
        additional-parameters: >
          factoryName=${{ secrets.ADF_NAME_UAT }}
        deployment-mode: Incremental